language: java
jdk:
- oraclejdk8
sudo: false
dist: trusty
script: mvn clean verify
after_success:
- git clone --depth=1 https://github.com/primeval-io/travis-ci-build-setup.git
- bash travis-ci-build-setup/maybe-deploy-snapshot.sh
env:
  global:
  - secure: J0dXeN7v8kCMjvoDlUHQlzgO3sjmgwLtBgvv9q4sIf8Vrm8y/tNPIT1vgKd/harKH8jMAihzEHV2sZw8NqGgiyIuPJ+Q+ChHUa8Y3pkpgcuk+RxZRV5XdmFlIa7qcSpa/ArPs77NSux1k7XgtyQbivqUkW+uYSqgTQrpLQ0H//HsjbLOBtf3+CfmBLhwHqNHQJcGYezg5IjXDkHXKV+KfMpj0WzzZOZxpnumBMwg9Bf+o1rFcxp8hYkWY+mtZKVATtXTUff2rz5VRDfo0RPSsXZeIDdozFBi+xiYxnzkF9RYGWKwZbsvs2Lc1hbhK+/TI+aSpqyrP9plk+HvHbDDK8N5LPlJYLrq7pBD2RAJ65GvoMJvyvFEp64cR1z5iBHRIjKkC/ZgK9hgSMoqKNsEqekLFcxxwqxRK77EBbcDB4t5nuY8IIkhM0OfvIeT6DcSI5kATCTu6KjvGOZs9B7eYkAyndyZKneDWfV4h8ZiDikSjh+Js0ObVto+7YLH4CxvrErH83E8kSkkYWt5hiJuIH1k9PlDiMd2l9g0xE5LIscVqXZpLTePvooMetvUjX8aZ4RyLFJSHuVaob1XCs6w1mykwqr7Dm5VnbWwwO9oqK6cLN20xasPOsC0XcnZBLREcIGXd2gKg748KMf/oKcsYZLhcwnHH6tYjMYbYJ18fzc=
  - secure: CqbNwnVWbRf8LBma5Kiprf9xBn6OL1c6W1upkSA6KdePSqOKbaQcE109gxCr5/tzYDZfuH6wbIMMuuCHoGuzbVLJsE42ey/T7LhtzWJ5vFUE9VmhuR3ahoHs+X+5bhamSr3DMb3fgnRJNWlWT0xhuKOeporemzh0AjKoFpcmV7IdDpcOb0eYjENvJjqJnRpQWFPmX39uV0ue9ajPMJ1Ke7eODWj2BgaxcFo1bJT1Eg3oQnTrwsnD4+nYsVRdAnq0Afq/DgY0E9RoQIjzuGoXd7C2oR1TS+2gfuDeXNRX1ZigCojVYRHzaKnVyJYiBC7Ka1oItUfM1AqPKt3p3JXWsmUrbyLn5buoqdRLOoOOF2WEkC1uL35DliEG44URgvjpPAgkfmM3m4JsWLykiMny9WUTFyN3snbwvsVVAQZY5UPhuJEPEN/Mmmi/DiN78fi9ojWPUWESXQPTnRAoW0kZrplIvJUxBMM7TWAMCZcZdRM0TbmiOfSBgqtlwvzB4zFVdbD2Xp1uG27r032/q91+f5a1LHsvCo2Zu8riujG1d/3yQuvI/8cvLkCk2zYkUzhxEjuPpPY6JHccPiNi03na/c//jRMpqfPGnZDCnOMH8aCgzcujYxdiWo34PQ4hk7N3bXMWfrczctb833ShNrb3EjWX7D5djXlriYkG4jhoYYw=
